# 📐 Module 5 · NumPy — Numerical Computing
### Course: Python from Scratch for Data Analysis

---

**Prerequisites:** Modules 1–4 — variables, control flow, lists, dictionaries, functions

### What you will learn today
1. Why NumPy: speed and vectorization
2. Creating 1D and 2D arrays
3. Vectorized arithmetic and boolean indexing
4. 2D indexing and slicing
5. Statistical functions: mean, std, percentile, argmax

> **Why NumPy matters for data analysis:** Every numerical library in Python — Pandas, Matplotlib, Seaborn, scikit-learn — is built on top of NumPy. Understanding arrays is the foundation of all data work.

---
## 🔷 Block 1 — From Lists to Arrays

### The problem with plain Python lists

You already know how to store numbers in a list. But what happens when you need to apply the same operation to every element?

In [1]:
# Apply 19% IVA tax to a list of prices — the plain Python way.
prices = [2500000, 850000, 1200000, 420000, 350000]

prices_with_tax = []
for p in prices:
    prices_with_tax.append(p * 1.19)
# Round 1: p = 2500000  →  2500000 * 1.19 = 2975000.0
# Round 2: p = 850000   →  850000  * 1.19 = 1011500.0
# Round 3: p = 1200000  →  1200000 * 1.19 = 1428000.0
# Round 4: p = 420000   →  420000  * 1.19 = 499800.0
# Round 5: p = 350000   →  350000  * 1.19 = 416500.0

print(prices_with_tax)

[2975000.0, 1011500.0, 1428000.0, 499800.0, 416500.0]


### Analogy: backpack vs. train car

A **Python list** is like a backpack — it holds anything: numbers, strings, booleans, even other lists. Very flexible, but operations happen one item at a time.

A **NumPy array** is like a train car — every seat holds the same type of passenger (all integers, or all floats). Because all seats are identical, the train can move all passengers at once — operations run in **parallel**, with no Python loop needed.

This is called **vectorization**.

In [2]:
import numpy as np

# The NumPy way — one line, no loop.
prices = np.array([2500000, 850000, 1200000, 420000, 350000])
prices_with_tax = prices * 1.19

print(prices_with_tax)

# Same result, but NumPy did the multiplication in compiled C code — much faster
# on large datasets (millions of rows).

[2975000. 1011500. 1428000.  499800.  416500.]


### Inspecting an array

Every NumPy array has attributes that describe its shape and contents.

In [3]:
import numpy as np

prices = np.array([2500000, 850000, 1200000, 420000, 350000])

print(f"Values : {prices}")
print(f"dtype  : {prices.dtype}")    # Data type of the elements.
print(f"shape  : {prices.shape}")    # Dimensions as a tuple.
print(f"ndim   : {prices.ndim}")     # Number of dimensions.
print(f"size   : {prices.size}")     # Total number of elements.

Values : [2500000  850000 1200000  420000  350000]
dtype  : int64
shape  : (5,)
ndim   : 1
size   : 5


### Creating arrays without typing every value

NumPy provides several functions to create standard arrays quickly.

In [9]:
import numpy as np

# All zeros — useful as a starting container.
zeros = np.zeros(5)
print(f"zeros     : {zeros}")

# All ones.
ones = np.ones(5)
print(f"ones      : {ones}")

# Evenly spaced values — like range() but for arrays.
# np.arange(start, stop, step)  — stop is EXCLUDED.
even_steps = np.arange(0, 10, 0.75)
print(f"arange    : {even_steps}")

# Evenly spaced values — you choose HOW MANY points.
# np.linspace(start, stop, num)  — stop is INCLUDED.
fine_grid = np.linspace(0, 1, 5)
print(f"linspace  : {fine_grid}")

zeros     : [0. 0. 0. 0. 0.]
ones      : [1. 1. 1. 1. 1.]
arange    : [0.   0.75 1.5  2.25 3.   3.75 4.5  5.25 6.   6.75 7.5  8.25 9.   9.75]
linspace  : [0.   0.25 0.5  0.75 1.  ]


### 🚨 Deliberate error — what happens when types don't match?

Read the error message carefully before scrolling to the fix.

In [10]:
import numpy as np

# An array of strings — fine on its own.
labels = np.array(["Laptop", "Phone", "Tablet"])
print(f"dtype: {labels.dtype}")

# Now try to do arithmetic on it — NumPy cannot multiply strings.
result = labels * 1.19   # <-- This will raise a TypeError.
print(result)

dtype: <U6


UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U6'), dtype('float64')) -> None

**What went wrong?** The array holds strings (`dtype='<U6'`), not numbers. NumPy is strict about types — unlike a Python list, it cannot hold a mix.

**Fix:** make sure your array contains numbers from the start.

In [11]:
import numpy as np

# Create a numeric array from the start — no strings.
prices = np.array([2500000, 850000, 1200000])
result = prices * 1.19
print(result)

[2975000. 1011500. 1428000.]


### ✏️ Exercise 1 — Total and average with NumPy (no loop)

**🧠 Before you code — apply the 5 steps:**

- **Input:** an array of 6 product prices in COP
- **Output:** the total sum and the average price

**Decompose:**
1. Create a NumPy array from six price values
2. Use a NumPy function to add all prices together → total
3. Use a NumPy function to compute the average → average

**Pseudocode:**
```
Create a collection of six prices.
Add all prices together → total price.
Divide total by the number of prices → average price.
Print both results.
```

**Pattern:** Accumulator — but vectorized (no explicit loop, NumPy handles it internally)

In [12]:
import numpy as np

# Six product prices in COP (Colombian pesos).
prices = np.array([2500000, 850000, 1200000, 420000, 350000, 980000])

# TODO: compute the total using a NumPy function (hint: np.sum).
total = np.sum(prices)

# TODO: compute the average using a NumPy function (hint: np.mean).
average = np.mean(prices)

# TODO: print both results with f-strings and {:,.0f} formatting.
print(f"Suma: {total:.0f}")
print(f"Promedio: {average:.0f}")

Suma: 6300000
Promedio: 1050000


---
## 🔷 Block 2 — Vectorized Operations

### Arithmetic on arrays

When you apply an arithmetic operator to a NumPy array, it applies to **every element** — no loop needed. This is called **element-wise** operation.

In [13]:
import numpy as np

# Two arrays of the same size.
units_sold  = np.array([45,  120, 30,  200, 15])
unit_prices = np.array([2500000, 1200000, 800000, 350000, 900000])

# Element-wise multiplication — position 0 * position 0, etc.
revenue = units_sold * unit_prices
print(f"Revenue per product: {revenue}")

# You can also combine with scalar arithmetic.
revenue_with_tax = revenue * 1.19
print(f"Revenue with IVA:    {revenue_with_tax}")

Revenue per product: [112500000 144000000  24000000  70000000  13500000]
Revenue with IVA:    [1.33875e+08 1.71360e+08 2.85600e+07 8.33000e+07 1.60650e+07]


### Analogy: broadcasting

**Broadcasting** is like a chef seasoning an entire tray of food at once instead of picking up each piece individually and adding salt.

When you write `prices * 1.19`, NumPy "broadcasts" the scalar `1.19` across every element — the scalar is applied to all items in one step.

In [14]:
import numpy as np

salaries = np.array([3200000, 4500000, 5100000, 2900000, 4800000])

# Add a 10% bonus to all salaries at once.
salaries_with_bonus = salaries * 1.10
print(f"Original salaries : {salaries}")
print(f"After 10% bonus   : {salaries_with_bonus}")

# Subtract social security (4%) from all at once.
net_salaries = salaries_with_bonus * (1 - 0.04)
print(f"Net salaries (4% deducted): {net_salaries}")

Original salaries : [3200000 4500000 5100000 2900000 4800000]
After 10% bonus   : [3520000. 4950000. 5610000. 3190000. 5280000.]
Net salaries (4% deducted): [3379200. 4752000. 5385600. 3062400. 5068800.]


### Comparison operators → boolean arrays

You can compare an array against a value. NumPy returns a **boolean array** — one `True`/`False` per element.

In [15]:
import numpy as np

grades = np.array([4.5, 2.1, 3.7, 1.8, 4.8, 3.0, 2.9])

# Which grades are passing (>= 3.0)?
is_passing = grades >= 3.0
print(f"Grades        : {grades}")
print(f"Passing mask  : {is_passing}")
# True where the condition is met, False where it is not.

Grades        : [4.5 2.1 3.7 1.8 4.8 3.  2.9]
Passing mask  : [ True False  True False  True  True False]


### Boolean indexing — replacing the Filter pattern

In Module 3 you learned the Filter pattern:
```
result = []  →  loop  →  if condition: result.append(x)
```

NumPy collapses that entire pattern into **one line**: pass a boolean array as the index.

> This does not mean you will never use the Filter pattern — but for numerical data, boolean indexing is faster and more readable.

In [16]:
import numpy as np

grades = np.array([4.5, 2.1, 3.7, 1.8, 4.8, 3.0, 2.9])

# --- Old way (Filter pattern with a loop) ---
passing_loop = []
for g in grades:
    if g >= 3.0:
        passing_loop.append(g)
# Round 1: g = 4.5  →  4.5 >= 3.0 is True   →  passing_loop = [4.5]
# Round 2: g = 2.1  →  2.1 >= 3.0 is False  →  passing_loop = [4.5]
# Round 3: g = 3.7  →  3.7 >= 3.0 is True   →  passing_loop = [4.5, 3.7]
# Round 4: g = 1.8  →  1.8 >= 3.0 is False  →  passing_loop = [4.5, 3.7]
# Round 5: g = 4.8  →  4.8 >= 3.0 is True   →  passing_loop = [4.5, 3.7, 4.8]
# Round 6: g = 3.0  →  3.0 >= 3.0 is True   →  passing_loop = [4.5, 3.7, 4.8, 3.0]
# Round 7: g = 2.9  →  2.9 >= 3.0 is False  →  passing_loop = [4.5, 3.7, 4.8, 3.0]
print(f"Loop result    : {passing_loop}")

# --- NumPy way (boolean indexing — one line) ---
passing_numpy = grades[grades >= 3.0]
print(f"NumPy result   : {passing_numpy}")

Loop result    : [np.float64(4.5), np.float64(3.7), np.float64(4.8), np.float64(3.0)]
NumPy result   : [4.5 3.7 4.8 3. ]


### 🚨 Deliberate error — mismatched array sizes

Read the error before looking at the fix.

In [17]:
import numpy as np

# Two arrays of DIFFERENT sizes.
prices = np.array([2500000, 850000, 1200000, 420000])
quantities = np.array([10, 5, 20])   # Only 3 elements — wrong!

# NumPy cannot add element-wise when sizes differ.
total = prices + quantities

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

**What went wrong?** NumPy requires both arrays to have the same shape for element-wise operations. There is no "auto-fill" for missing values.

**Fix:** make sure both arrays have the same length.

In [18]:
import numpy as np

prices     = np.array([2500000, 850000, 1200000, 420000])
quantities = np.array([10, 5, 20, 8])   # Now 4 elements — matches.

total = prices * quantities
print(f"Total value per product: {total}")

Total value per product: [25000000  4250000 24000000  3360000]


### ✏️ Exercise 2 — Find all passing grades (vectorized Filter)

**🧠 Before you code — apply the 5 steps:**

- **Input:** an array of 8 student grades (scale 0.0–5.0)
- **Output:** an array containing only the grades that are >= 3.0

**Decompose:**
1. Create a NumPy array with 8 grade values
2. Compare each grade against 3.0 → produces a boolean array
3. Use that boolean array as an index to select only the passing grades
4. Print the results and the count of passing students

**Pseudocode:**
```
Create a collection of eight grade values.
Check which grades meet or exceed the passing threshold → a True/False mask.
Use that mask to keep only the passing grades → filtered collection.
Print filtered grades and how many there are.
```

**Pattern:** Filter — vectorized with boolean indexing

In [19]:
import numpy as np

# Grades for 8 students (scale 0.0 to 5.0).
grades = np.array([4.5, 2.1, 3.7, 1.8, 4.8, 3.0, 2.9, 3.5])

# TODO: create a boolean mask for grades >= 3.0.
passing_mask = grades>=3.0

# TODO: use the mask to filter the array.
#usamos el array booleano para filtrar en el array grades las notas>=3.0
passing_grades = grades[passing_mask]

# TODO: print the passing grades and the count.
print(passing_grades)
print(passing_grades.size)

[4.5 3.7 4.8 3.  3.5]
5


---
## 🔷 Block 3 — Indexing and Slicing

### 1D indexing — same rules as lists

If you already know how to index a list, you already know how to index a 1D NumPy array.

In [20]:
import numpy as np

grades = np.array([4.5, 2.1, 3.7, 1.8, 4.8, 3.0, 2.9])

print(f"First grade     : {grades[0]}")      # Index 0.
print(f"Last grade      : {grades[-1]}")     # Index -1 = last.
print(f"Grades 1 to 3   : {grades[1:4]}")    # Slice — stop excluded.
print(f"Every other one : {grades[::2]}")    # Step = 2.
print(f"Reversed        : {grades[::-1]}")   # Step = -1.

First grade     : 4.5
Last grade      : 2.9
Grades 1 to 3   : [2.1 3.7 1.8]
Every other one : [4.5 3.7 4.8 2.9]
Reversed        : [2.9 3.  4.8 1.8 3.7 2.1 4.5]


### 2D arrays — the spreadsheet model

A 2D array has **rows** and **columns**. Think of it as a spreadsheet:
- Rows are observations (e.g., products)
- Columns are variables (e.g., months)

You index with `arr[row, col]` — **row first, then column**.

```
          Month 0  Month 1  Month 2  Month 3
Product A   120      135       98      150
Product B   200      180      220      195
Product C    45       60       55       70
```

In [21]:
import numpy as np

# 3 products × 4 months of sales (units sold).
sales = np.array([
    [120, 135,  98, 150],   # Product A
    [200, 180, 220, 195],   # Product B
    [ 45,  60,  55,  70],   # Product C
])

print(f"Shape  : {sales.shape}")   # (3 rows, 4 columns)
print(f"ndim   : {sales.ndim}")    # 2 dimensions.
print(f"size   : {sales.size}")    # 3 * 4 = 12 total elements.

Shape  : (3, 4)
ndim   : 2
size   : 12


In [22]:
import numpy as np

sales = np.array([
    [120, 135,  98, 150],   # Row 0 — Product A
    [200, 180, 220, 195],   # Row 1 — Product B
    [ 45,  60,  55,  70],   # Row 2 — Product C
])

# Single element — row 1, column 2 (Product B in month 2).
print(f"Product B, Month 2      : {sales[1, 2]}")

# Entire row 0 — all months for Product A.
print(f"Product A (all months)  : {sales[0, :]}")

# Entire column 2 — all products in month 2.
print(f"All products in month 2 : {sales[:, 2]}")

# Submatrix — rows 0 and 1, months 0 and 1.
print(f"Top-left 2x2 block:\n{sales[0:2, 0:2]}")

Product B, Month 2      : 220
Product A (all months)  : [120 135  98 150]
All products in month 2 : [ 98 220  55]
Top-left 2x2 block:
[[120 135]
 [200 180]]


### Fancy indexing — selecting non-consecutive rows or columns

You can pass a **list of indices** instead of a slice to pick specific rows or columns in any order.

In [23]:
import numpy as np

sales = np.array([
    [120, 135,  98, 150],   # Row 0 — Product A
    [200, 180, 220, 195],   # Row 1 — Product B
    [ 45,  60,  55,  70],   # Row 2 — Product C
])

# Select rows 0 and 2 (Product A and Product C) — skip Product B.
selection = sales[[0, 2], :]
print(f"Products A and C:\n{selection}")

# Select columns 1 and 3 (months 1 and 3 only).
months_1_3 = sales[:, [1, 3]]
print(f"Months 1 and 3:\n{months_1_3}")

Products A and C:
[[120 135  98 150]
 [ 45  60  55  70]]
Months 1 and 3:
[[135 150]
 [180 195]
 [ 60  70]]


### ✏️ Exercise 3 — Which product sold the most in month 2?

**🧠 Before you code — apply the 5 steps:**

- **Input:** the sales 2D array (3 products × 4 months)
- **Output:** the name of the product with the highest sales in month 2 (column index 1)

**Decompose:**
1. Extract all values from column 1 (month 2) → a 1D array of 3 values
2. Find the index of the maximum value in that column
3. Use the index to look up the product name from a list

**Pseudocode:**
```
Extract column number one from the sales grid → a short list of three sales figures.
Find which position in that list holds the largest number → winning index.
Use the winning index to look up the product name → winner.
Print the result.
```

**Pattern:** Tracker — find the position of the maximum value

> **Before running:** predict which product has the highest sales in month 2 by reading the array above.

In [24]:
import numpy as np

products = ["Product A", "Product B", "Product C"]

sales = np.array([
    [120, 135,  98, 150],   # Product A
    [200, 180, 220, 195],   # Product B
    [ 45,  60,  55,  70],   # Product C
])

# TODO: extract column 1 (month 2) as a 1D array.
month2_sales = sales[:, 1]

# TODO: find the index of the maximum value (hint: np.argmax).
best_index = np.argmax(month2_sales)

# TODO: use best_index to get the product name from the products list.
best_product =products[best_index]

# TODO: print the result.
print(f"El producto con mayores ventas es: {best_product}")

El producto con mayores ventas es: Product B


---
## 🔷 Block 4 — Statistical Functions

NumPy provides fast built-in functions for descriptive statistics. You will use these constantly in data analysis.

In [ ]:
import numpy as np

# Salaries for 6 employees (COP).
salaries = np.array([3200000, 4500000, 5100000, 2900000, 4800000, 3750000])

print(f"Sum        : {np.sum(salaries):,.0f} COP")
print(f"Mean       : {np.mean(salaries):,.0f} COP")
print(f"Median     : {np.median(salaries):,.0f} COP")
print(f"Std dev    : {np.std(salaries):,.0f} COP")
print(f"Min        : {np.min(salaries):,.0f} COP")
print(f"Max        : {np.max(salaries):,.0f} COP")
print(f"75th pct   : {np.percentile(salaries, 75):,.0f} COP")

### argmax and argmin — finding the position of extreme values

`np.argmax()` and `np.argmin()` return the **index** of the maximum or minimum value — not the value itself. This is useful for looking up corresponding labels.

In [ ]:
import numpy as np

employees = ["Valentina", "Santiago", "Camila", "Andrés", "Daniela", "Felipe"]
salaries  = np.array([3200000, 4500000, 5100000, 2900000, 4800000, 3750000])

highest_idx = np.argmax(salaries)
lowest_idx  = np.argmin(salaries)

print(f"Highest paid : {employees[highest_idx]} ({salaries[highest_idx]:,} COP)")
print(f"Lowest paid  : {employees[lowest_idx]}  ({salaries[lowest_idx]:,} COP)")

### The axis parameter — operating on rows or columns of a 2D array

When you call `np.sum(arr)` on a 2D array without `axis`, it sums **all elements** into one number. The `axis` parameter lets you choose a direction:

- `axis=0` — **collapse rows** (operate vertically, result has one value per column)
- `axis=1` — **collapse columns** (operate horizontally, result has one value per row)

**Analogy:** imagine pressing the array flat like a pancake.
- `axis=0`: press it **downward** — each column gets squashed into one number.
- `axis=1`: press it **sideways** — each row gets squashed into one number.

In [ ]:
import numpy as np

# 3 products × 4 months of sales.
sales = np.array([
    [120, 135,  98, 150],   # Product A
    [200, 180, 220, 195],   # Product B
    [ 45,  60,  55,  70],   # Product C
])

# No axis — single total for the entire array.
total_all = np.sum(sales)
print(f"Grand total (all products, all months) : {total_all}")

# axis=1 → sum across columns → one total per ROW (per product).
total_per_product = np.sum(sales, axis=1)
print(f"Total per product (axis=1)             : {total_per_product}")
# Product A: 120+135+98+150 = 503
# Product B: 200+180+220+195 = 795
# Product C: 45+60+55+70 = 230

# axis=0 → sum across rows → one total per COLUMN (per month).
total_per_month = np.sum(sales, axis=0)
print(f"Total per month   (axis=0)             : {total_per_month}")
# Month 0: 120+200+45 = 365
# Month 1: 135+180+60 = 375
# Month 2: 98+220+55  = 373
# Month 3: 150+195+70 = 415

In [ ]:
import numpy as np

sales = np.array([
    [120, 135,  98, 150],
    [200, 180, 220, 195],
    [ 45,  60,  55,  70],
])

# Average sales per product (across all 4 months).
avg_per_product = np.mean(sales, axis=1)
print(f"Avg per product : {avg_per_product}")

# Average sales per month (across all 3 products).
avg_per_month = np.mean(sales, axis=0)
print(f"Avg per month   : {avg_per_month}")

# Which product has the highest average?
best_product_idx = np.argmax(avg_per_product)
print(f"Best product index: {best_product_idx}  (avg = {avg_per_product[best_product_idx]:.1f} units)")

### ✏️ Exercise 4 — Full analysis with axis

**🧠 Before you code — apply the 5 steps:**

- **Input:** the 3×4 sales array; a list of product names
- **Output:** total per product, average per month, name of the product with the highest average

**Decompose:**
1. Compute the total units sold per product → one number per row (use axis=1)
2. Compute the average units sold per month → one number per column (use axis=0)
3. Find the index of the product with the highest average
4. Look up the product name using that index
5. Print all results

**Pseudocode:**
```
Add up all months for each product → a total per product.
Average all products for each month → an average per month.
Find which product position has the largest average → winning index.
Use the winning index to find the product name → winner.
Print totals, averages, and the winner.
```

**Pattern:** Accumulator (axis=1 for totals) + Tracker (argmax for winner)

> **Before running:** predict which product will have the highest average.

In [ ]:
import numpy as np

products = ["Product A", "Product B", "Product C"]

sales = np.array([
    [120, 135,  98, 150],   # Product A
    [200, 180, 220, 195],   # Product B
    [ 45,  60,  55,  70],   # Product C
])

# TODO: total units sold per product (sum along axis=1).
total_per_product = None   # Replace None with your code.

# TODO: average units sold per month (mean along axis=0).
avg_per_month = None   # Replace None with your code.

# TODO: index of the product with the highest average.
best_idx = None   # Replace None with your code.

# TODO: product name corresponding to best_idx.
best_name = None   # Replace None with your code.

# TODO: print all results.
pass

---
## 🔷 Block 5 — Mini-Project: Sales Dashboard

You will now combine everything from this module to build a small sales analysis report.

**Context:** a Colombian electronics retailer tracks monthly unit sales for 5 products over 6 months. You need to compute totals, revenues, identify the best and worst months, and find the top-selling product.

In [ ]:
import numpy as np

# --- Dataset (define once, reuse throughout all parts) ---

products   = ["Laptop", "Phone", "Tablet", "Headphones", "Monitor"]
months     = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"]

# Monthly sales in units — shape: (5 products × 6 months).
sales = np.array([
    [ 45,  52,  38,  61,  55,  48],   # Laptop
    [120, 135, 110, 145, 130, 125],   # Phone
    [ 30,  28,  35,  42,  38,  31],   # Tablet
    [200, 215, 195, 230, 210, 205],   # Headphones
    [ 15,  18,  12,  20,  17,  14],   # Monitor
])

# Unit price per product in COP.
unit_price = np.array([2500000, 1200000, 800000, 350000, 900000])

print(f"Sales grid shape : {sales.shape}  (products × months)")
print(f"Products         : {products}")
print(f"Months           : {months}")

### Full problem decomposition (no Python syntax yet)

**PART A — Total units and revenue per product:**
- For each product, add up all 6 months of sales → total units sold.
- Multiply each product's total units by its unit price → total revenue in COP.

**PART B — Best and worst month overall:**
- Add up all products for each month → total units sold per month.
- Find which month position has the highest total → best month index.
- Find which month position has the lowest total → worst month index.

**PART C — Find the top-selling product:**
- Use the total units array from Part A.
- Find the position of the maximum value → index of top product.
- Look up the name using that index.

**PART D — Print the formatted report.**

In [ ]:
import numpy as np

products   = ["Laptop", "Phone", "Tablet", "Headphones", "Monitor"]
sales = np.array([
    [ 45,  52,  38,  61,  55,  48],
    [120, 135, 110, 145, 130, 125],
    [ 30,  28,  35,  42,  38,  31],
    [200, 215, 195, 230, 210, 205],
    [ 15,  18,  12,  20,  17,  14],
])
unit_price = np.array([2500000, 1200000, 800000, 350000, 900000])

# --- PART A: Total units and revenue per product ---

# TODO: sum across axis=1 to get total units per product.
total_units = None   # Replace with your code.

# TODO: multiply total_units by unit_price (element-wise) to get revenue.
total_revenue = None   # Replace with your code.

# TODO: print total units and revenue for each product.
# Hint: use a for loop with enumerate() over products.
pass

In [ ]:
import numpy as np

months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"]
sales = np.array([
    [ 45,  52,  38,  61,  55,  48],
    [120, 135, 110, 145, 130, 125],
    [ 30,  28,  35,  42,  38,  31],
    [200, 215, 195, 230, 210, 205],
    [ 15,  18,  12,  20,  17,  14],
])

# --- PART B: Best and worst month ---

# TODO: sum across axis=0 to get total units per month.
total_per_month = None   # Replace with your code.

# TODO: find the index of the best month (argmax) and worst month (argmin).
best_month_idx  = None   # Replace with your code.
worst_month_idx = None   # Replace with your code.

# TODO: print the results.
pass

In [ ]:
import numpy as np

products = ["Laptop", "Phone", "Tablet", "Headphones", "Monitor"]
sales = np.array([
    [ 45,  52,  38,  61,  55,  48],
    [120, 135, 110, 145, 130, 125],
    [ 30,  28,  35,  42,  38,  31],
    [200, 215, 195, 230, 210, 205],
    [ 15,  18,  12,  20,  17,  14],
])

# --- PART C: Top-selling product ---

# Recompute total units (from Part A) so this cell is self-contained.
total_units = np.sum(sales, axis=1)

# TODO: find the index of the product with the highest total units.
top_product_idx = None   # Replace with your code.

# TODO: look up the product name.
top_product_name = None   # Replace with your code.

# TODO: print the result.
pass

In [ ]:
import numpy as np

# Full dataset (self-contained cell for the final report).
products   = ["Laptop", "Phone", "Tablet", "Headphones", "Monitor"]
months     = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"]
sales = np.array([
    [ 45,  52,  38,  61,  55,  48],
    [120, 135, 110, 145, 130, 125],
    [ 30,  28,  35,  42,  38,  31],
    [200, 215, 195, 230, 210, 205],
    [ 15,  18,  12,  20,  17,  14],
])
unit_price = np.array([2500000, 1200000, 800000, 350000, 900000])

# Compute all values needed for the report.
total_units     = np.sum(sales, axis=1)
total_revenue   = total_units * unit_price
total_per_month = np.sum(sales, axis=0)
best_month_idx  = np.argmax(total_per_month)
worst_month_idx = np.argmin(total_per_month)
top_idx         = np.argmax(total_units)

# --- PART D: Print the formatted report ---
# TODO: replace each pass/None with the actual print statements.

print("=" * 50)
print("  SALES DASHBOARD — H1 REPORT")
print("=" * 50)

print("\nUnits sold and revenue per product:")
print(f"  {'Product':<12} {'Units':>8}  {'Revenue (COP)':>16}")
print(f"  {'-'*40}")
for i in range(len(products)):
    # TODO: print each product's name, total_units[i], and total_revenue[i].
    pass

print(f"\n  Best month  : {months[best_month_idx]}  ({total_per_month[best_month_idx]:,} units)")
print(f"  Worst month : {months[worst_month_idx]}  ({total_per_month[worst_month_idx]:,} units)")
print(f"  Top product : {products[top_idx]}  ({total_units[top_idx]:,} units)")
print("=" * 50)

---
## 🏠 Homework — Module 5

**Estimated time:** 25–30 min
**Rules:** Create a new file called `homework_module5.py`. Type everything from scratch.

---

### The problem: grade analyzer for a university course

A teacher has recorded grades for 5 students across 3 exams.

```python
import numpy as np

student_names = ["Valentina", "Santiago", "Camila", "Andrés", "Daniela"]

grades = np.array([
    [4.5, 3.8, 4.2],   # Valentina
    [2.1, 2.8, 3.0],   # Santiago
    [3.7, 4.0, 3.5],   # Camila
    [1.8, 2.0, 1.5],   # Andrés
    [4.8, 4.5, 4.9],   # Daniela
])
```

Write the following analysis in `homework_module5.py`:

1. **Average per student** — compute each student's average across the 3 exams (use `axis=1`)
2. **Top student** — find the student with the highest average (use `argmax`)
3. **Failing students** — find all students with an average below 3.0 (use boolean indexing)
4. **Class average per exam** — compute the class average for each of the 3 exams (use `axis=0`)
5. **Formatted report** — print a clean report that includes all four results above

### Expected output format
```
==========================================
  GRADE REPORT
==========================================
  Average per student:
    Valentina : 4.17
    Santiago  : 2.63
    Camila    : 3.73
    Andrés    : 1.77
    Daniela   : 4.73
------------------------------------------
  Top student    : Daniela (avg = 4.73)
  Failing students (avg < 3.0):
    Santiago  (2.63)
    Andrés    (1.77)
------------------------------------------
  Class average per exam:
    Exam 1 : 3.38
    Exam 2 : 3.42
    Exam 3 : 3.42
==========================================
```

### Bonus (optional)
Add a 6th task: find the exam on which the class performed best and the exam on which it performed worst.

---
*Delivery: bring `homework_module5.py` to the next session. It must run without errors.*

In [ ]:
# homework_module5.py  — starter code
# Run this file with:  python homework_module5.py

import numpy as np

student_names = ["Valentina", "Santiago", "Camila", "Andrés", "Daniela"]
exam_labels   = ["Exam 1", "Exam 2", "Exam 3"]

grades = np.array([
    [4.5, 3.8, 4.2],   # Valentina
    [2.1, 2.8, 3.0],   # Santiago
    [3.7, 4.0, 3.5],   # Camila
    [1.8, 2.0, 1.5],   # Andrés
    [4.8, 4.5, 4.9],   # Daniela
])

# 1. Average per student (axis=1).
# TODO: compute avg_per_student using np.mean.
avg_per_student = None   # Replace None with your code.

# 2. Top student.
# TODO: use np.argmax on avg_per_student to find the index.
top_idx = None
top_name = None

# 3. Failing students (average < 3.0).
# TODO: create a boolean mask and filter student_names and avg_per_student.
# Hint: convert student_names to a NumPy array so you can apply boolean indexing.
student_names_arr = np.array(student_names)
failing_mask   = None   # Replace None with your code.
failing_names  = None   # Replace None with your code.
failing_avgs   = None   # Replace None with your code.

# 4. Class average per exam (axis=0).
# TODO: compute avg_per_exam using np.mean.
avg_per_exam = None   # Replace None with your code.

# 5. Print the formatted report.
# TODO: print the report using the variables above.
pass

---
## 📋 Module 5 Summary

| Concept | Syntax | Key point |
|---------|--------|-----------|
| Import NumPy | `import numpy as np` | Always aliased as `np` |
| Create array | `np.array([1, 2, 3])` | All elements must be the same type |
| Array attributes | `.dtype`, `.shape`, `.ndim`, `.size` | Inspect before operating |
| Zeros / ones | `np.zeros(n)`, `np.ones(n)` | Useful as initial containers |
| Range array | `np.arange(start, stop, step)` | Stop is excluded |
| Evenly spaced | `np.linspace(start, stop, n)` | Stop is included; n = count of points |
| Vectorized math | `arr * 1.19` | No loop needed; applied to every element |
| Broadcasting | `scalar op array` | Scalar is applied to all elements |
| Boolean array | `arr >= 3.0` | Returns True/False per element |
| Boolean indexing | `arr[arr >= 3.0]` | Replaces the Filter pattern for numbers |
| 2D indexing | `arr[row, col]` | Row first, then column |
| Row slice | `arr[i, :]` | All columns of row i |
| Column slice | `arr[:, j]` | All rows of column j |
| Fancy indexing | `arr[[0, 2], :]` | Non-consecutive rows or columns |
| Sum / mean | `np.sum(arr)`, `np.mean(arr)` | Works on full array or per axis |
| Std / median | `np.std(arr)`, `np.median(arr)` | Descriptive statistics |
| Percentile | `np.percentile(arr, 75)` | 75th percentile |
| Position of max/min | `np.argmax(arr)`, `np.argmin(arr)` | Returns index, not value |
| Axis parameter | `np.sum(arr, axis=0)` | 0 = collapse rows; 1 = collapse columns |

**Next module:** Pandas Fundamentals — working with tables of data using DataFrames 📊